# Generated by Django 4.1.7 on 2023-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('pizza_crust', models.CharField(choices=[('N', 'Normal'), ('T', 'Thin'), ('TH', 'Thick'), ('GF', 'Gluten Free')], max_length=2)),
                ('pizza_sauce', models.CharField(choices=[('T', 'Tomato'), ('BBQ', 'Barbeque'), ('ST&G', 'Sundried Tomato & Garlic')], max_length=4)),
                ('pizza_cheese', models.CharField(choices=[('M', 'Mozzarella'), ('P', 'Parmesan'), ('D', 'Double Cheese'), ('LF', 'Low Fat')], max_length=2)),
                ('pizza_toppings', models.CharField(choices=[('PE', 'Pepperoni'), ('CH', 'Chicken'), ('HA', 'Ham'), ('PI', 'Pineapple'), ('PEP', 'Peppers'), ('M', 'Mushrooms'), ('O', 'Onions')], max_length=3)),
            ],
        ),
    ]
